Excel toolkit #175 code style
BHoM/Excel_UI pull request #198
Opened 2020-02-19 14:55 UTC by awakeman

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #175 
Closes #193 

- Moved all one-line if statement bodies to new line. (#175)
- Reordered Methods/Constructors/Properties/Fields into groups (#193)
- Added headers for groups (#193)
- Added method separators (#193)

### Test files

N/A

### Changelog

### Additional comments

2020-02-21 03:46 UTC, adecler requested changes
- Going in the right direction for Excel_UI although there are still a few problems and you have skipped a couple of files. Also inconsistent format for your separator comments on some of your files.

- Nothing done on Excel_Engine

2020-02-21 03:46 UTC, adecler commented on Excel_UI/Addin/AddIn.cs
> +        private Dictionary<string, CallerFormula> m_formulea;
Incorrect variable naming. Please re-read details in issue #193

2020-02-21 03:46 UTC, adecler commented on Excel_UI/Addin/AddIn.cs
> +        private Dictionary<string, CallerFormula> m_formulea;
Same for all other private variables

2020-02-21 03:46 UTC, adecler commented on Excel_UI/UI/Callers/Explode.cs
> +
Incorrect format for the properties

2020-02-21 03:46 UTC, adecler commented on Excel_UI/UI/Components/Adapter/CreateAdapter.cs
> +        /*******************************************/
- Incorrect format for first property

2020-02-21 03:46 UTC, adecler commented on Excel_UI/UI/Components/Adapter/CreateAdapter.cs
> +        /*******************************************/
Same in other files

2020-03-02 14:01 UTC, awakeman commented
Spoke with @al-fisher and we agreed it would be expedient to allow for someone other than @adecler to pick up this review in his absence as this is otherwise blocking other tasks on this toolkit. obviously reviewer should review against @adecler's comments to check they are appropriately addressed.

2020-03-02 17:27 UTC, FraserGreenroyd requested changes
I did a review against:
 - The original issues this PR aims to solve
 - The comments made by @adecler 

I will admit, this is a little tricky for me as I've been out of the loop on any discussions. However, in the interest of allowing this PR to move forward and unblock you @awakeman  I have made only one suggestion - if the suggestion is invalid, please let me know and I am happy to then give an approving review instead.

I acknowledge that there may be other coding improvements which need to be made, and I may have missed some of the finer points which @adecler would be after in this PR. However, I believe the pragmatic view, given the current circumstances, is to allow this PR to merge (pending decision on my requested change) and allow @adecler to review again on his return and raise new issues as appropriate. I hope this will be acceptable to all concerned :smile:

2020-03-02 17:27 UTC, FraserGreenroyd commented on Excel_UI/UI/Templates/CallerFormula.cs
> +        private IExcelSelectorMenu m_Menu;
Should this be at the bottom of the file?

2020-03-03 02:57 UTC, adecler submitted a review, later dismissed
Thanks @FraserGreenroyd for picking this up and apologies for my absence.

Still a few things left to do on top of the comment from Fraser:

- In `AddIn.FlagUsed()`, `Wb` should be `wb`. Even better would be to use a more explicit name. Same in `Project.SaveData()`
- `Properties.Transpose()` has no separator and should in the private section.
- In `Properties.GetPropertyDictionaries()`, `else` should be on a new line. Same for `Project.GetId()` and `Project.Deserialise()`
- `Explode.m_Native` should be in the private field section
- `SingleOptionCallerFormula.MenuRoot` incorrect section and format.
- ArrayResizer` and `DebugConfig` not done

A few things on compliance as well. Although I am happy for those to be done on a separate PR as it was not part of this scope but thought I would mention it while I noticed them.

- Inconsistencies with file naming vs method naming (e.g. `FromExcel` vs `ToBHoM`, `Note` vs `SetNote`, `TextRef` vs `RefText`)
- Incorrect naming of `Query` methods: should not start with `Get`
- `Timer` should be in an `Objects` folder

2020-03-04 10:53 UTC, awakeman commented
> * In `AddIn.FlagUsed()`, `Wb` should be `wb`. Even better would be to use a more explicit name. Same in `Project.SaveData()`
Fixed
> * `Properties.Transpose()` has no separator and should in the private section.
Fixed
> * In `Properties.GetPropertyDictionaries()`, `else` should be on a new line. Same for `Project.GetId()` and `Project.Deserialise()`
Fixed
> * `Explode.m_Native` should be in the private field section
Fixed
> * `SingleOptionCallerFormula.MenuRoot` incorrect section and format.
Fixed
> * ArrayResizer`and`DebugConfig` not done
Fixed


> A few things on compliance as well. Although I am happy for those to be done on a separate PR as it was not part of this scope but thought I would mention it while I noticed them.
> 
> * Inconsistencies with file naming vs method naming (e.g. `FromExcel` vs `ToBHoM`, `Note` vs `SetNote`, `TextRef` vs `RefText`)
> * Incorrect naming of `Query` methods: should not start with `Get`
> * `Timer` should be in an `Objects` folder

This will be addressed in a compliance PR once this is merged

2020-03-04 11:26 UTC, FraserGreenroyd approved these changes
Have gone through this again in the spirit of unblocking for more PRs and improvements. I am happy that @adecler second changes appear to be resolved so am approving this for merging to unblock future work. I accept I may have missed something @adecler may find, but would recommend we go for a new issue to resolve that to allow this to move forward with Excel UI.

2020-03-04 11:29 UTC, merged