Adding Excel_Adapter
BHoM/Excel_UI pull request #199
Opened 2020-02-20 10:16 UTC by LMarkowski

### Issues addressed by this PR

This is a draft of an Excel_Adapter created for the purposes of the [RevitRebar addin](https://github.com/BuroHappoldLegacySoup/RevitRebar). For now it only contains one method parsing an excel spreadsheet into BHoM Data.oM `Table` as that is one functionality I needed. I open this PR to start a discussion if it's worth further developing.

This is the second BHoM project created by me so I'm happy to hear any complaints/suggestions about the code structure, references, etc.

2020-02-20 10:19 UTC, pawelbaran commented
@awakeman I believe you are best positioned to lead @LMarkowski to get this turned into a scalable solution - are you OK with taking it? I am happy to support locally when needed.

2020-02-20 15:33 UTC, rolyhudson reviewed
I had a quick look at this and put in a couple of comments. I don't have a machine with excel on it so have not run it and tested it.
Would be good to have a test file for when I have access to a machine with Excel.
There may be some bigger things to consider and maybe other libraries which would make the short term goal easier.
Long term BHoM goals are of not needing more than open source software. I wonder if a library like https://github.com/ClosedXML could be considered? So we can do read writes to excel docs without excel installed. 
My limited experience of using ``Microsoft.Office.Interop.Excel`` and ``closedXML`` suggest that ``closedXML`` is solid / well  documented and easier to use for basic things at least.

2020-02-20 15:33 UTC, rolyhudson commented on Excel_Adapter/Read/ParseExcelSpreadSheet.cs
> +            _Worksheet xlWorksheet = xlWorkbook.Sheets[1];
What if we have multiple sheets? Should we read them all or allow the user to specific which one?

2020-02-20 15:33 UTC, rolyhudson commented on Excel_Adapter/Read/ParseExcelSpreadSheet.cs
> +
Don't get the last column last cell from ``xlWorksheet.UsedRange``? Looks like you are searching for them maybe this is unnecessary?

2020-02-20 15:33 UTC, rolyhudson commented on Excel_Adapter/Read/ParseExcelSpreadSheet.cs
> +                        row[head] = x.Cells[i, j].Value2.ToString();
Are we only dealing with strings or should the method handle numeric types too?

2020-02-21 09:46 UTC, LMarkowski commented on Excel_Adapter/Read/ParseExcelSpreadSheet.cs
> +
I did it that way at first but it didn't always return correct value. I found this way more reliable.

2020-02-21 09:48 UTC, LMarkowski commented on Excel_Adapter/Read/ParseExcelSpreadSheet.cs
> +            _Worksheet xlWorksheet = xlWorkbook.Sheets[1];
Yes, of course. It can be split into two methods, one returning all sheets as `List<Table>` and another returning specified sheet.

2020-02-21 09:49 UTC, LMarkowski commented on Excel_Adapter/Read/ParseExcelSpreadSheet.cs
> +                        row[head] = x.Cells[i, j].Value2.ToString();
In my case most of values were strings. Eventually it should be extended.

2020-02-21 10:46 UTC, LMarkowski commented
@rolyhudson, thanks for feedback. I'll take a look into that library. It's a good point to use open-source soft as often as possible.

Another issue to consider is whether we want the output to be in a form of Data.oM Table. It's good because it's from BH.oM but `DataTable` class forces declaring names and types of each column before filling them with data. It works best when we have matching input data. We could name columns in some more generic way than I did, or maybe change output type for 2D generics matrix. Or keep both solutions.

2020-02-24 09:20 UTC, IsakNaslundBh requested changes
Some general comments if we want to turn this into an actual BHoM-style adapter:

- Need to add an ExcelAdapter class that is inheriting from the BHoMAdapter
  - Would store the file path on the adapter itself, i.e. let the adapter open the workbook for you.
- All calls to the adapter should be done via the main methods on the base adapter, this is Push/Pull/Update/Delete/Execute atm. For Pull, requests can be added that fit excel if need be.
  - For the example method added by you @LMarkowski , I would start with Pull, and adding a for example `WorkSheetRequest` that pulls all information from a provided worksheet. THis would also resolve @rolyhudson s comment https://github.com/BHoM/Excel_Toolkit/pull/199/files#r382069412
- Namespace for the adapter project should be BH.Adapter.Excel

I think these are the first main comments regarding the general formatting. @alelom has the adapter template been updated after the last refactoring? Not sure how much it would help for this case, but could potentially help with some of the initial setup.

Then whether to use Office Interop or closed XML, I do not know myself, but like @rolyhudson s suggestion about being able to read write without a need for office!

2020-02-24 10:48 UTC, rolyhudson commented
@IsakNaslundBh thanks for those notes. 
I am keen to get involved here to get to grips with adapters if that is OK @LMarkowski? Although not wanting to step on any toes or planned work. 
Also I have the need to write to excel so I will probably start on the C and U of CRUD. Happy to test and comment on the R.
Recent conversation with @alelom suggests referring to the updated adapter wiki https://github.com/BHoM/documentation/wiki/Introduction-to-the-BHoM_Adapter 
Also that Tedds_Toolkit https://github.com/BuroHappoldEngineering/Tedds_Toolkit is the most recent to be set up according to the template so may also be a good ref.

2020-02-24 13:14 UTC, rolyhudson commented
Just looking for good adapter reference to help me understand how this should be / could be done. I'm finding that the FileAdapter is quite helpful I don't find the Tedds_Toolkit very helpful as I don't think it is well developed enough yet. What do you think here @alelom?

2020-02-24 13:52 UTC, rolyhudson commented
Just had a quick look and try at setting out the template required for this - nothing actually implemented but using the FileAdapter as key reference. Have a look here @LMarkowski  and see what you think: https://github.com/BHoM/Excel_Toolkit/tree/TemplateMethodsForExcelAdapter. This is assuming we are working with reading and writing to and from xlsx files. But I think this can be achieved via Sockets. Not too sure of the pros and cons of the two approaches.

2020-03-02 10:44 UTC, LMarkowski commented
Ok, I had a look into the ClosedXML and I think we could make a good use of it. Didn't think of that in this way but as BHoM is meant to be open source it is indeed a good idea to avoid closed source libraries as long as it is not inevitable.
So @rolyhudson, what do you think of using your branch for a template as it is much more BHoM-like than my draft? I could then rewrote my reader into ClosedXML, and merge it to your branch.
I actually didn't have any explicit plan of further work on this adapter. Published it to see if there's gonna be a demand for it. And as we can see - there is. 😉 
Also, sorry for my late reply. I just switched for a part-time last week and got a bit inundated with tasks.

2020-04-08 15:29 UTC, FraserGreenroyd commented
Following discussion with @IsakNaslundBh and @rolyhudson during PR merge day, the following actions should be taken for this PR:

 - Raise issues which link to this discussion (either @LMarkowski or @rolyhudson to handle)
 - Work on a new branch as a new draft PR

This PR is being closed as it will not be merged but does serve as valid conversations around the Excel adapter functionality so should be linked to in suitable issues.

2020-04-08 15:29 UTC, closed without merging