Excel toolkit #197 dynamic formulae
BHoM/Excel_UI pull request #208
Opened 2020-03-05 12:10 UTC by awakeman

### Issues addressed by this PR

Closes #197 

Dynamically registers the formula when selected from CTRL+SHIFT+B menu or ribbon menu and serialises used method component requests into hidden sheet.

Raising this as a draft because there is a bug i've been fighting since yesterday when using CreateData components (that should be identical in functionality with CreateEnum, which is unaffected) that i can't get to the bottom of. I'd appreciate some fresh eyes on it.

### Test files

### Changelog

### Additional comments

2020-03-12 10:49 UTC, awakeman commented
@IsakNaslundBh This is now ready for review, testing on your existing sheets should one time load all methods and (if saved) on future loads only the methods that are in use.

2020-03-12 11:07 UTC, awakeman commented
Some of this work has increased my awareness of trying to reduce the use of COM Interop over the C APIs, much of the tasks that use the COM API could be refactored, raising an issue to look into this going forward. #209

2020-03-13 09:57 UTC, awakeman commented
Adding do not merge to this because, in my opinion, it carries too much risk to rush into including it in the upcoming beta. Will lift this on 30th March.

2020-03-13 14:11 UTC, IsakNaslundBh commented
@awakeman , Still have some issues loading up excel files created before these changes:

See https://burohappold.sharepoint.com/:f:/s/BHoM/EtPmoptuJq1Hmvm2C44eXCQBHcznPACr62Vny6IZq7-aIg?e=VTcezX

2020-03-17 16:35 UTC, IsakNaslundBh requested changes
Issue with loading pre-existing files resolved, issue was I had opened them in a build from before this PR was ready. Now seem to be working as expected, being able to open old sheets with things loading correctly, and can use them again after.

Some other issues found:

1. Create enum menu is empty:

![image](https://user-images.githubusercontent.com/22005920/76878668-7284f580-6875-11ea-8459-18deed249d6b.png)


2. Tweaks to enum (adding an item) leads to com call crash for the validation. This can be tested by storing a pushtype from before and after the following PR https://github.com/BHoM/BHoM_Adapter/pull/205

2020-04-01 12:21 UTC, awakeman commented
Issue #187 has been made worse (occurs most time) so needs resolving as part of this PR.

2020-04-03 09:58 UTC, rwemay commented
Great to see this thanks @awakeman . I've added a file to the meta tests - link below. Similar to @IsakNaslundBh , I can open old sheets, but am having some issues. Specifically for example, the formula `Create.Structure.Loads.Loadcase?by_String_Int32_LoadNature()` isn't working, and intellisense not coming up for it. 

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FExcel%5FToolkit%2F%5FMacro&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

2020-04-03 10:26 UTC, awakeman commented
> Similar to @IsakNaslundBh , I can open old sheets, but am having some issues. Specifically for example, the formula `Create.Structure.Loads.Loadcase?by_String_Int32_LoadNature()` isn't working, and intellisense not coming up for it.

Just to clarify you mean accessing it through `ctrl`+`shift`+`b` right.

2020-04-09 09:00 UTC, rwemay commented
> > Similar to @IsakNaslundBh , I can open old sheets, but am having some issues. Specifically for example, the formula `Create.Structure.Loads.Loadcase?by_String_Int32_LoadNature()` isn't working, and intellisense not coming up for it.
> 
> Just to clarify you mean accessing it through `ctrl`+`shift`+`b` right.

The methods don't seem to show up in either intellisense or ctrl + shift + b - that is methods that were already in the spreadsheet previously. Methods that were not in the spreadsheet previously seem to load. Could it be an issue of ignoring methods already used in old spreadsheets?

2020-04-15 09:19 UTC, rwemay commented
Latest issues with this PR: 
 - [ ] Deprecated methods not being registered for old sheets - @awakeman need to be registered. 
 - [ ] Create enum and create object not working - @awakeman need to rebase from master
 - [ ] Tooltips/intellisense not showing up - @awakeman rebase from master?
 - [ ] Crash on exit worse now, needs stepinto/investigation

2020-04-20 10:38 UTC, rwemay commented
Hi @awakeman , any joy with crash on exit? We're looking to close this PR so may separate out crash on exit. One thing that is still not working (although is ticked above) is intellisense. @IsakNaslundBh  and I have looking into this, and it seems to be due to deprecated methods. We've put a couple of sheets in the folder below, and I'll email you separately the formula/location worth testing but basically: 

 - For some methods in old spreadsheets, they aren't registered and intellisense doesn't work;
 - If you open up a fresh Excel sheet, and use ctrl+shift+b or the menu to create the same method _then_ open the sample sheet, then the method and intellisense works fine. So something to do with opening an old sheet versus registering the formula in Excel before you open said sheet.

2020-04-20 17:02 UTC, rwemay commented
@awakeman , with the last commit, intellisense now working. I think park the crash on exit for now as I don't think is a new issue and good to get this PR merged. I was able to recreate the enum bug, and I think @IsakNaslundBh already reported this - it was on the Apater/Pull enum rather than acoustic (apologies) below for ease of ref.

![image](https://user-images.githubusercontent.com/15233608/79778687-12301a80-8331-11ea-8f45-a3f0a247ec19.png)

2020-04-23 06:58 UTC, rwemay commented
@awakeman @IsakNaslundBh , this fixes the enum issue (although it did seem to exacerbate showing the xlDNA warning dialogue). I just tested the 'deprecated' sheet in the test script folder this morning, and it looks like the RobotAdapter is not working. I can create a new one from the Ribbon, and then the formula is registered, but it's not registering the formula from the sheet. The adapter method should not have changed between versions. Apologies, I didn't pick this up before the last commit - I didn't think it was an issue but can't see what might have caused it in last commit.

2020-04-28 06:20 UTC, rwemay commented
Hi @IsakNaslundBh , @awakeman , any updates on the adapter issue just above, were either of you able to reproduce in the 'deprecated' spreadsheet in the test folder?

2020-04-28 07:17 UTC, IsakNaslundBh commented
> Hi @IsakNaslundBh , @awakeman , any updates on the adapter issue just above, were either of you able to reproduce in the 'deprecated' spreadsheet in the test folder?

Not working for me either. If I add a new RobotAdapter in any other cell, the one in the initial cells kiscks in though, so looks like some missed registration to me.

2020-04-30 14:34 UTC, rwemay commented
@awakeman , as mentioned, we need to make sure Engine.GetProperty() and Engine.SetProperty() formulae still work. They seem to have changed to GetPropertyCaller.Components.GetProperty?by_Object_String() in this PR.

2020-05-01 08:10 UTC, rwemay commented
@kayleighhoude , good if you can help test this to get it over the line - we need to make sure all of the sheets you're using currently work with this PR, as well as the issues identified.

2020-05-01 20:21 UTC, kayleighhoude reviewed
Ran tests on 3 separate workflows:
- [x] Enum menu appears
- [x] Internalise retaining information between sessions (woohoo!)
- [x] Gets and sets retaining their information
- [x] Reopen on crash not happening anymore

1 workbook has 4 sheets with pulls on each for about 50 objects, and upon opening and attempting to set a pull to false/true the program fails (this is a consistent issue)
![image](https://user-images.githubusercontent.com/34316256/80838721-a9b22a80-8bc7-11ea-9cdb-3a8b0e51affc.png)
^or upon opening this runs over and over again

2020-05-01 20:27 UTC, rwemay commented
Does Engine.GetProperty still work for you on this PR @kayleighhoude ?

2020-05-01 20:32 UTC, kayleighhoude commented
@rwemay it was working on all of the Revit properties that I was getting in those workflows

2020-05-20 17:25 UTC, kayleighhoude commented
@awakeman heads up that i'm working off of the same branch now (post cleaning up my build folder and moving fresh Excel UI, Engine and oM dlls over to BHoM in the Roaming folder)

2020-05-20 17:33 UTC, rwemay commented
For the final updates to this PR, can we also set copy local on the BHoM_Engine to false? 

https://github.com/BHoM/Excel_Toolkit/issues/227

2020-06-01 14:36 UTC, rwemay commented
@al-fisher , @IsakNaslundBh , I've pushed up the changes discussed, centralising a lot of the formula name code to the Caller template. This is currently dependent on the branch in BHoM_UI just below - but as we said, hoping to get that merged ahead so no need to rename branches/rePR etc. 

https://github.com/BHoM/BHoM_UI/tree/BHoM_UI-%23272-Add-GetFullName()-method-for-callers

2020-06-05 10:20 UTC, rwemay commented
@awakeman @IsakNaslundBh @kayleighhoude @al-fisher need to look at the adapter formulae as with my last push there's a bit of repetition. 

@kayleighhoude @awakeman can you build my latest and test - see what you think of the formulae - essentially adding BH.Engine or BH.oM across the board to keep things 1:1. The post builds should work now such that you _don't_ need to build BHoM_UI - only this toolkit/branch for testing (thanks @IsakNaslundBh ). We need to get this fully tested and merged by Tuesday next week(!!)

2020-06-05 10:52 UTC, IsakNaslundBh submitted a review, later dismissed
wrong path for BHoM_Engine

2020-06-05 10:52 UTC, IsakNaslundBh commented on Excel_UI/Excel_UI.csproj
> +      <HintPath>..\..\..\..\..\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
this needs to be changed to exact path

2020-06-05 10:55 UTC, awakeman commented on Excel_UI/Excel_UI.csproj
> +      <HintPath>..\..\..\..\..\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
Thanks, I spotted just after too.

2020-06-10 08:32 UTC, rwemay approved these changes
Approving on the basis of having (hopefully) fixed the crash on close but. Concious that there are issues on formulae which we will raise and squash today with any luck. If not then apologies for breaking changes on formulae in the alpha installers/master branch...

2020-06-10 08:33 UTC, merged