Adapter prototype
BHoM/Excel_UI pull request #241
Opened 2020-07-23 10:58 UTC by rolyhudson

Updated version of #222 
For discussion of #221 
   
### Issues addressed by this PR
Read and write (tables only for now)

### Test files
[Push and Pull Table](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Issues/Issue221-Adapter?csf=1&web=1&e=J6zhkF)

2020-07-23 12:17 UTC, rwemay commented
I had to close the workbooks to make both pull/push work (didn't do much investigation into settings etc.). Seems to work pretty well though, and can see massive potential for this to 'print out' (or read in) pre-formatted data tables. Great stuff.

2020-07-23 12:21 UTC, rwemay commented
On styles, I'm not sure if you're using/creating MS styles specifically, but could be one to think about. We've some styles built into some of the templates, and could perhaps pull these for use, and/or have an input that matches them by name - to save a lot of Grasshopper (or other UI) components in creating the styles outside of the Excel interface. We should have some BHoM objects that carry the style eventually (sorry if I've missed these/they exist already!). 

![image](https://user-images.githubusercontent.com/15233608/88285674-70311d00-cce7-11ea-9aa5-e098e48cfd05.png)

2020-07-23 12:41 UTC, rolyhudson commented
> I had to close the workbooks to make both pull/push work (didn't do much investigation into settings etc.). Seems to work pretty well though, and can see massive potential for this to 'print out' (or read in) pre-formatted data tables. Great stuff.

Yes bit of a restriction there. When using ClosedXML as the files cannot be in use. But no need for Excel installed.

2020-07-23 12:50 UTC, rolyhudson commented
@rwemay On styles:
Nothing really happening here yet with styles. 
Just a glimmer of an idea that maybe everything stylistic can be generalised with a [CSS ruleset syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#CSS_rulesets) `selector {declaration, declaration...} ` 
Which could I think be extended to cover web stuff, dataviz, excel...
With pre-templated files that may not be necessary - but the opportunity to apply styles across toolkits using some standard (with great default settings) objects is quite appealing.

2020-07-23 12:53 UTC, rwemay commented
We can always look at alternatives for creating a live link, building on sockets with specific components if necessary. XML will give much wider benefits for read/write. Maybe one thing we could do here is provide a user with a mores specific warning to close the file.

2020-07-24 16:38 UTC, AndreBalasian commented
Good development @rolyhudson .
ClosedXML lends itself really well for this type of work with spreadsheets.
I look forward to using and enhancing this to generate reports and read data without having to rely on Excel running in the background.

2020-07-26 18:17 UTC, AndreBalasian submitted a review, later dismissed
Well written code and good implementation of ClosedXML.

The only optional recommendation as a precautionary measure is to add a 1 second time delay after writing to an excel file in order to give Windows more time to finalise the file closing process.

2020-07-27 09:18 UTC, awakeman requested changes

2020-07-27 09:18 UTC, awakeman commented on Excel_oM/Excel_oM.csproj
> +      <HintPath>..\..\..\..\..\..\..\ProgramData\BHoM\Assemblies\Data_oM.dll</HintPath>
This should be an absolute path.

2021-11-17 18:46 UTC, pawelbaran commented
@rolyhudson I guess we could close this one as we have https://github.com/BHoM/Excel_Toolkit/pull/320 now?

2021-12-06 11:39 UTC, pawelbaran commented
Closing this as https://github.com/BHoM/Excel_Toolkit/pull/320 got merged.

2021-12-06 11:39 UTC, closed without merging