Fix internalise bug on spill arrays
BHoM/Excel_UI pull request #339
Opened 2022-03-21 03:48 UTC by adecler

### Issues addressed by this PR

Closes #315

The internalise function was replacing the formula of each cell with its string representation in order. This means that, as soon as the first cell of an expanded array was replaced, all the other cells would loose their value (since they don't contain a formula themselves). To fix this, we are now using the cached value of each cell. 

### Test files
https://burohappold.sharepoint.com/:f:/s/BHoM/EoFSYhhfB7VIo83fGEiQZksBx-GMQJ2upK1nbYfLvpYHIQ?e=Nui359

2022-03-21 05:37 UTC, adecler commented
@BHoMBot check compliance

2022-03-21 05:51 UTC, adecler commented
@BHoMBot check required

2022-03-21 10:13 UTC, FraserGreenroyd approved these changes
**Test report**

I downloaded the test script provided, and attempted the steps described within the test script.

I first ran the steps against todays test beta artefact and confirmed the bug occurred on the test script. I closed the script without saving, checked out this branch, and compiled this branch on top of the beta artefact. I opened the test script and reran the steps.

After selecting the internalise option on the data highlighted, on the beta this resulted in only the first row of data existing. On this branch, all rows of data continued to exist after internalising.

**Not tested**

I have not tested any other functionality of Excel Toolkit nor followed the test procedure in the testing of this pull request.

**Result**

I am happy to approve this pull request based on the test I have undertaken. In the interest of ensuring valid tests on beta artefacts, I will merge this at 4pm UTC at the latest, or on a second review, whichever occurs first. @kayleighhoude @alexissantella could you therefore please test this PR as a priority when you start to detect if there are further issues. If unable, I'll merge at 4pm UTC and we can continue testing on beta artefacts before the 5.1 beta later this week.

2022-03-21 15:16 UTC, kayleighhoude commented
Getting to this testing now

2022-03-21 15:56 UTC, kayleighhoude requested changes, later dismissed
![image](https://user-images.githubusercontent.com/34316256/159298869-c7fcf5c8-7f0f-4c09-a7f7-509a6d2176eb.png)
Pre-testing on branch

When selecting all of the cells- they internalise individually:
![image](https://user-images.githubusercontent.com/34316256/159300011-13cdccc5-4553-4cbc-a386-ec7fa7801771.png)

I accidentally just clicked on the first one and hit internalise and it collapsed them again (shouldn't it just internalise that first object? and leave the rest alone?):
![image](https://user-images.githubusercontent.com/34316256/159300241-846b27c2-239e-4889-9057-0fc6ffb2bb6b.png)

2022-03-22 05:26 UTC, adecler commented
@kayleighhoude ,

The behaviour you are complaining about is exactly the same you would get by using the standard copying by value in both cases. I would stick to my policy of replicating behaviours that an expert Excel user would expect from native Excel functionality.

@FraserGreenroyd , I will leave the final decision to you but I am personally happy to merge this PR despite Kayleigh's comment.

2022-03-22 15:15 UTC, FraserGreenroyd commented
I have retested based on @kayleighhoude comments, and while I can experience the same concern, I have also confirmed this occurs with native Excel components. As such, I am in agreement with @adecler that this is default Excel behaviour and should not be addressed at this time, certainly not within the scope of this PR.

This PR brings in a benefit to the codebase, in fixing the issue of internalising a selection of cells which have previously been expanded, and as such I see benefit to including this in the 5.1 beta later this week. Owing to the approving review from myself, and the confirmation from @kayleighhoude in their review that this PR does resolve the originally reported issue, I am merging this PR for distribution in the final beta test artefacts ahead of the final beta release at the end of this week.

If there are more items to discuss, or questions, as part of this work, I recommend raising them as new issues for appropriate discussion 😄

2022-03-22 15:16 UTC, merged