Typo in Internalise data button description
BHoM/Excel_UI pull request #353
Opened 2022-07-19 15:54 UTC by andrewengh

### Issues addressed by this PR

Closes #352
When hovering over the 'Internalise data' button in the excel bhom UI ribbon, the description of the button contains a typo. Currently says, 'Save the value of the selected cells so it will stil lbe available when the file is reopened.' Needs to be changed to 'Save the value of the selected cells so it will still be available when the file is reopened.'

### Test files
None

### Changelog

- `GetCustomUI()` - Typo addressed

### Additional comments

2022-07-19 15:56 UTC, dengh0 commented
@BHoMBot check required

2022-07-19 16:02 UTC, FraserGreenroyd requested changes

2022-07-19 16:02 UTC, FraserGreenroyd commented on Excel_UI/Ribbon/Ribbon.cs
> +                <button id='internalise' onAction='Internalise' label='Internalise data' imageMso='RecordsSaveRecord' supertip='Save the value of the selected cells so it will still be available when
```suggestion
                <button id='internalise' onAction='Internalise' label='Internalise data' imageMso='RecordsSaveRecord' supertip='Save the value of the selected cells so that the values will be available when the file is reopened.' />
```

I think this reads slightly better given the function of the action? Thoughts @dengh0 ?

2022-07-19 16:05 UTC, dengh0 commented on Excel_UI/Ribbon/Ribbon.cs
> +                <button id='internalise' onAction='Internalise' label='Internalise data' imageMso='RecordsSaveRecord' supertip='Save the value of the selected cells so it will still be available when
Yeah I agree!

2022-07-21 20:19 UTC, FraserGreenroyd approved these changes
This looks great now, thanks @dengh0 

Only thing that will need fixing before merge is the PR title - it shouldn't contain the `Excel_UI-#352` element (see [here](https://github.com/BHoM/documentation/wiki/Changelog) for guidelines), and an appropriate label depicting the `type` of PR this is (also for the change log). I'd recommend `type:documentation` based on the code changes. Then the last 2 checks can be triggered and it's good to go.

2022-07-21 21:25 UTC, dengh0 commented
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2022-07-21 21:28 UTC, dengh0 commented
@BHoMBot check ready-to-merge

2022-07-22 08:35 UTC, merged