Implement ValueList Caller to use Excel DataValidation
BHoM/Excel_UI pull request #62
Opened 2019-01-15 10:17 UTC by awakeman

This uses Excel Data Validation when run to provide the user with a list of options for `MultiChoiceCaller` (`CreateEnumCaller` and `CreateDataCaller`).

Works reasonably nicely though there are some limitations:

- The formula can't persist in the cell, it is replaced by a value and the validation is added to the cell. So it's more of a one-shot utility function.
- Currently with `CreateData` the objects in the list do not persist across save, close, reopen as they are not serialised. This will need to be addressed before approval at a minimum. Since the formula is gone `Ctrl`+`Alt`+`F9` will not bring them back as it will with formula. Simplest solution would be to serialise them along with the rest but the serialisation/internalisation feature is under discussion in #55 so could change.

Conflict: Has an identical change in common with #60 so will (under rebase at least) probably result in a trivially resolved conflict. I'll be sure to handle that myself on whichever PR is left standing when one is merged. Shown below:
https://github.com/BHoM/Excel_Toolkit/commit/89f1384e8202b62dc91a027b8145585815d7db63#diff-db4b3d1bb8c74131e06aeb62f7a9230bR83
https://github.com/BHoM/Excel_Toolkit/commit/00e637bfd873a9a6d81262a6fe032206474c95ea#diff-db4b3d1bb8c74131e06aeb62f7a9230bR83

This feels a lot more consistent when used in conjunction with #61 but neither are dependent on the other and work independently, hence keeping the PRs separate and single-purpose.

2019-01-15 10:41 UTC, awakeman commented
Little demo:

![excel_bhom_validation](https://user-images.githubusercontent.com/18450341/51175369-0fcf4d00-18b2-11e9-88a3-2fae669990e5.gif)

2019-01-15 11:38 UTC, IsakNaslundBh commented
Works well for me for the enums!

For the serialisation of the Data, could we instead of serialising the actual data, serialise the method and inputs that was used to create the data in the first place? A bit cautious that some of the serialised data sets could grow to be quite big, leading to unnecessarily long load and save times.

2019-01-15 11:53 UTC, awakeman commented
>For the serialisation of the Data, could we instead of serialising the actual data, serialise the method and inputs that was used to create the data in the first place? 

Yes and no, it should be trivial enough to to that in a very simple case, but we'll need to track changes like crazy to make sure we follow it around. Moving cells, inserting rows/columns, autofilling, etc. will all require a cell reference to be updated (or new cells to be added to the watchlist in the case of copying/autofilling) which is a complex feature and may also hurt performance.

2019-01-15 12:38 UTC, IsakNaslundBh commented
> Yes and no, it should be trivial enough to to that in a very simple case, but we'll need to track changes like crazy to make sure we follow it around. Moving cells, inserting rows/columns, autofilling, etc. will all require a cell reference to be updated (or new cells to be added to the watchlist in the case of copying/autofilling) which is a complex feature and may also hurt performance.

Yes ok, that makes sense. Depending what we end up with in the chats regarding serialisation, might be worth always adding anything from a CreateData instance to the serialised data then, if that is easy enough to implement. Good thing about it is that we only need to serialise it once for each DataSet as well, and it should all follow, so might for a case with many cells using a fairly small dataset actually be less data to serialise then, I presume!

Only problem with this is if any of the DataSets are updated. They should be fairly static, but might require tweaks every now and then after changes made in the BHoM.

2019-01-15 12:43 UTC, awakeman commented
>Only problem with this is if any of the DataSets are updated. They should be fairly static, but might require tweaks every now and then after changes made in the BHoM.

Indeed, the same if an Enum is updated, this will currently not do anything ton update that.

2019-01-16 12:48 UTC, awakeman commented
I won't push it now but I have now got a version that makes use of a change introduced in #69 and internalises the data in the drop-down so that the aforementioned issue is fixed.

2019-01-17 14:08 UTC, awakeman commented
That's now done. I'm personally now happy with this feature as it addresses my main concern:

>Currently with CreateData the objects in the list do not persist across save, close, reopen as they are not serialised. This will need to be addressed before approval at a minimum. Since the formula is gone Ctrl+Alt+F9 will not bring them back as it will with formula.

2019-01-17 16:12 UTC, IsakNaslundBh requested changes
Enums are working fine.

Creating some data using CreateData, then saving then reopening throws this error:
![image](https://user-images.githubusercontent.com/22005920/51331642-78692600-1a7a-11e9-96a0-5980efd4ae07.png)

Hitting yes then gives this:

![image](https://user-images.githubusercontent.com/22005920/51331677-89199c00-1a7a-11e9-9937-50d978748273.png)

After that, the data validation is gone for the data cells, as well as for any enums in the same sheet. The data is fixed to the value at last save. This value is working though, for both enums and BHoMObejcts.

2019-01-17 16:14 UTC, awakeman commented
I've not seen this, what data are you creating?

2019-01-17 16:18 UTC, IsakNaslundBh commented
When testing I used concrete material and some random enums. See attached:

[Test BHoM Data.xlsx](https://github.com/BHoM/Excel_Toolkit/files/2769563/Test.BHoM.Data.xlsx)

2019-01-17 16:23 UTC, awakeman commented
Yeah, with concrete I can reproduce independently. will look into it. Thanks.

2019-01-17 16:50 UTC, awakeman commented
OK, with some inspection it appears to be related to the settings directly in the validation itself, you can remove the `BHoM_DataHidden` sheet and the error about it being corrupt persists. Will look into seeing if i can reproduce by hand and find what the cause is.

2019-01-17 17:02 UTC, awakeman commented
Right, found the problem, a delimited list for excel validation is capped at 255 characters. It lets you do it programatically but won't load a saved file where this happens.

Will look into resolving tomorrow but it may be that we leave `CreateData` out for now.

A range reference will work, but i am wary of creating loads of new special ranges around the place.

2019-02-04 10:47 UTC, awakeman commented
@IsakNaslundBh bump

2019-02-04 13:25 UTC, IsakNaslundBh commented
File no longer corrupted.

Values in the data fields can not be evaluated though. Explode and/or get property fails.

Reevaluating the sheet by ctrl+shift+f9 get the whole thing working again, but not working when just opening the sheet.

![image](https://user-images.githubusercontent.com/22005920/52210738-2ef54500-2888-11e9-9844-931bd3564062.png)

In an ideal solution, these members should not need to be internalised, but able to be picked up from the datasets in the BHoMData.

2019-02-04 13:34 UTC, awakeman commented
They are no longer internalised, the extra hidden sheet is a formula that expands from the data sets when evaluated, which is why you need to use `Ctrl`+`Shift`+`F9` and is consistent with #69.

2019-02-13 15:16 UTC, IsakNaslundBh approved these changes

2019-02-13 15:18 UTC, merged