Use more complete namespaces for Formula names
BHoM/Excel_UI pull request #96
Opened 2019-05-31 14:23 UTC by awakeman

#### WARNING: Breaks existing Excel documents if they use affected methods

   
### Issues addressed by this PR

Closes #94

Uses the full namespace bar the `BH.oM.`/`BH.Engine.`/`BH.Adapter.` at the start.

In the case of a Create method it uses the namespace of the resulting type, not the engine method (this matches Grasshopper and the menu structure). e.g. `Create.Structure.Elements.Bar` instead of `Create.Structure.Bar` due to the engine method being `BH.Engine.Structure.Create.Bar` and not `BH.Engine.Structure.Elements.Create.Bar`.

### Test files
N/A Have a look at the registered formulae or see what is placed in the cell when picking from a menu. The above example of `Create.Structure.Elements.Bar` is one, it is `Create.Structure.Bar` on `master`

### Changelog

#### Fixed
- Namespace for formulae only taking the last part of the namespace.

### Additional comments

#### WARNING: Breaks existing Excel documents if they use affected methods

2019-05-31 14:25 UTC, awakeman commented
@jdarcyBHE @johannaisak @IsakNaslundBh I believe this will break your Loadcases and Combinations template so it will need updating with this merge.

2019-06-03 08:23 UTC, johannaisak commented
@njsmithies FYI

2019-06-05 09:43 UTC, FraserGreenroyd requested changes
Doesn't look like this quite works, screenshot below and as discussed, suggestion in code for where issue appears to be. I presume it should be `Create.Environment.Panel` rather than `Panel.Environment.Panel`?

![image](https://user-images.githubusercontent.com/18049174/58946847-a9729a80-877e-11e9-8a3b-bf3e4bd06dc5.png)

2019-06-05 09:43 UTC, FraserGreenroyd commented on Excel_UI/UI/Components/oM/CreateObject.cs
> +                    return decltype.Name + "." + ns + "." + Caller.Name;
Should this not be `category` instead?

2019-06-05 09:44 UTC, FraserGreenroyd commented on Excel_UI/UI/Templates/CallerFormula.cs
> +                    return decltype.Name + "." + ns + "." + Caller.Name;
Should this not be `category` instead?

2019-06-05 10:08 UTC, awakeman commented on Excel_UI/UI/Components/oM/CreateObject.cs
> +                    return decltype.Name + "." + ns + "." + Caller.Name;
Not category actually, but should be `Create`

2019-06-05 10:08 UTC, awakeman commented on Excel_UI/UI/Templates/CallerFormula.cs
> +                    return decltype.Name + "." + ns + "." + Caller.Name;
nah, not here, it is correct here.

2019-06-05 10:20 UTC, awakeman commented
@FraserGreenroyd Should be resolved now.

2019-06-05 10:30 UTC, FraserGreenroyd approved these changes
That looks more in line with the raised issue. Looked at a couple of objects, seems fine to me. I have only looked at Environmental based objects and engine methods so one of the Structures team may need to take a look as well but from my side, all good :smile:

![image](https://user-images.githubusercontent.com/18049174/58949732-05402200-8785-11e9-9dfe-d24d24f52fa2.png)

2019-06-07 14:19 UTC, merged