Excel toolkit issue85 startup performance
BHoM/Excel_UI pull request #99
Opened 2019-06-06 08:06 UTC by awakeman

### Issues addressed by this PR

Closes #85 

It now defers adding items to the context menus until a workbook is opened and does so in background threads, I believe there is some locking going on in the COM interface still as it is a little sluggish whilst it does it but it does seem to complete faster than when it was done fully synchronously. Not entirely happy with it for this reason but struggling to find a better method. It was my hope that there would be some event to hook into as each sub-menu was opened so that we could build the menu on demand but it appears the MS Office API doesn't provide one.

### Test files
N/A. Open excel, open/create new workbook, compare load times.

### Changelog

### Additional comments

2019-06-06 16:33 UTC, rwemay commented
I built this and tried to open Excel/the multistorey spreadsheet in test library and it crashed twice on opening. On the third attempt Excel opened the sheet a bit faster than it was doing, but was then unresponsive for a minute + once it was open. 

I don't think this is the solution - what's the next option? 

If it's the context menu that's the problem, why don't we just disable this for now? With global search (is that in the works?) and in-cell formulae, we'll have to manage until there is a solution.

2019-06-07 06:22 UTC, michaldengusiak commented
Could we add this a part of Excel Ribbon?
This would allow us to open excel quickly and then enable via Ribbon?

2019-06-07 08:33 UTC, awakeman commented
Yeah, realistically I think the next solution is to disable the menu but give a mechanism for the user to manually enable it. The performance of the COM API (the only way to manipulate the context menus/ribbon) is bad and we're registering thousands of buttons 99% of which are likely unused for any given session. As I said above excel gives us no way to to this lazily in order to not do the redundant work.

Will back this out and do that.

2019-06-07 14:11 UTC, awakeman commented
@rwemay, @michaldengusiak I think I have a bit of a middle-of-the road solution.

First off I've reverted to only presenting the BHoM menus on the normal "Cell" context menu, so it will not work from print preview or tables anymore and secondly I don't populate menus with more than 200 leaf nodes in the menu tree automatically, the user is instead presented with a button to load them on demand. 

![image](https://user-images.githubusercontent.com/18450341/59110040-2431e600-8936-11e9-90da-6cccd9ef11eb.png)

Clicking this does close the menu so you have to navigate it twice to get to the thing you want.

Coupled with bumping up the priority of the Global Search (#56) though should release some of the pain here.

For me this brings the load time down below 30s.

2019-06-10 09:18 UTC, awakeman commented
I've added some profiling capability so that we can capture the load times and break it down to some critical parts. See below:

Before:
![image](https://user-images.githubusercontent.com/18450341/59185233-cedd1b00-8b67-11e9-9eb0-eb5302af2175.png)

After:
![image](https://user-images.githubusercontent.com/18450341/59185415-50cd4400-8b68-11e9-821d-49898a098789.png)

Here is the sheet to test for yourself:

[profiling.xlsx](https://github.com/BHoM/Excel_Toolkit/files/3271384/profiling.xlsx)

You will need to compare with `Excel_Toolkit-issue85-BaselinePerformanceWithProfiling` branch, which is just mater with the additional commit that adds the profiling stuff `cherry-pick`ed in.

2019-06-10 09:30 UTC, rwemay commented
Please add 'plugin disabled' to the profiles, as this is obviously the base benchmark.

2019-06-10 09:34 UTC, awakeman commented
I can't use the BHoM to time Excel opening without the BHoM, needless to say it is still considerably faster.

2019-06-10 12:50 UTC, rwemay commented
Thanks @awakeman , as discussed, I think adding the non-BHoM loading baseline is important. If it cant be coded/calculated exactly, I would start by simply timing the opening from double click, with BHoM disabled. We do need to measure the impact we make to user experience so we can communicate this/test against it. Hopefully its all short term anyway, once we resolve the load performance in a scalable manner.

2019-06-10 13:03 UTC, awakeman commented
@rwemay all that is being timed above is the time it takes to load the BHoM Addin, so the reference for when it is disabled is 0. i.e. the above is how much time is being added by the BHoM plugin under the conditions of my PC. The specific number will vary based on a number of factors specific to the user and specific to the situation (e.g. how loaded the CPU is at the moment the application is opened). The important part is the relative difference, 5-6x improvement.

2019-06-11 06:47 UTC, rwemay commented
This appears to force the view in open mode to be 'normal view' even if files is saved in sheet/print view(?) Test file below. Load time is still relatively long. Please make sure to benchmark with BHoM not loaded at all - that would rule out any events/lag with metrics not currently measured/that we aren't aware of. 

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Excel_Toolkit-Issue97-Null%20causing%20lists%20to%20fail?csf=1&e=VPaZ18

2019-06-11 12:50 UTC, awakeman commented
Looking into this now. As for expected behaviour it is worth looking at #46, #78 and #79 (and the PRs that solve them) to see discussion on how to treat empty inputs and the conflicting possibilities of how we could do so.

2019-06-11 20:52 UTC, awakeman commented
Had a conversation with @rwemay and we agreed to kill the context menu entirely for now. For him the delayed loading wasn't working anyway.

Focus will now move to Global search. Would be good to get some fresh eyes on bringing back the context menu without poor performance in the future @al-fisher @IsakNaslundBh.

2019-06-11 20:55 UTC, michaldengusiak commented
@awakeman  `context menu` you mean search using right click ? this means we will be only able to type formulas for time being?...

2019-06-11 22:54 UTC, rwemay commented
Thats correct @michaldengusiak . Until there is a working and tested version of the context menu it will be disabled. In interim we will need to use formulae and/or the ctrl shift B menu when it implemented. If you have time to help @awakeman  with either/or solution, feel free to pitch in.

2019-06-12 05:30 UTC, rwemay requested changes

2019-06-12 05:30 UTC, rwemay commented on Excel_UI/UI/Templates/SelectorMenu_CommandBar.cs
>                  }
Does this relate to the context menu/trying to limit the number of items loaded, only? If so please remove - it didn't work when I tested, and in any case is not relevant if we're not loading the context menu.

2019-06-12 05:30 UTC, rwemay commented on Excel_UI/UI/Templates/SingleOptionCallerFormula.cs
>          /*******************************************/
Should we not remove the method altogether if removing the body?

2019-06-12 05:30 UTC, rwemay commented on Excel_UI/UI/Templates/CallerFormula.cs
> -
Have we exhausted all options of creating the context menu? (e.g. what's the cost of 'FindControl'/is it required? - I assume yes as it looks like the previous single caller did not have this).

2019-06-12 06:27 UTC, rwemay commented
Looking at the errors and warnings that show up on startup, I'm also wondering if there are gains in resolving/removing some of these (e.g. not trying to load RhinoCommon)? I suspect based on the earlier profiling these aren't big gains. See output file below. 

@awakeman , please make sure all test scripts are saved to the test script folder. I have created one for you for this issue. It is very important to follow this, particularly as test files/scripts may contain a mix of internal/external namespaces, references and information. 

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Excel_Toolkit-Issue85-Startup%20Performance?csf=1&e=BQo1Bm

2019-06-12 08:08 UTC, awakeman commented on Excel_UI/UI/Templates/CallerFormula.cs
> -
The single caller inherited it from this one. Yes it is required to create the sub-menu for each category only once.

2019-06-12 08:08 UTC, awakeman commented on Excel_UI/UI/Templates/SelectorMenu_CommandBar.cs
>                  }
yeah, I will remove.

2019-06-12 08:09 UTC, awakeman commented on Excel_UI/UI/Templates/SingleOptionCallerFormula.cs
>          /*******************************************/
It's a constructor, it still needs to forward its parameters to the base constructor.

2019-06-12 08:33 UTC, awakeman commented
Merging in #102 on request of @rwemay 

<!-- PLEASE ENSURE YOU REVIEW THE CONTENT OF EACH PR CAREFULLY, INCLUDING SUBSEQUENT COMMENTS BY YOURSELF OR OTHERS. -->
<!-- IN PARTICULAR PLEASE ENSURE THAT SENSITIVE OR INAPPROPRIATE INFORMATION IS NOT UPLOADED -->
   
### Issues addressed by this PR
<!-- Add reference(s) to issue(s) solved by this PR. Please use keyword Fixes/Closes as per https://help.github.com/articles/closing-issues-using-keywords/ -->

Closes #101

As of #96 the leading part of the namespace for Create methods uses the namespace of the type it returns, in order to file methods where they are expected. an example being `Create.Structure.Elements.Bar` as opposed to `Create.Structure.Bar`, the create method for which resides in `BH.Engine.Structure.Create` and not `BH.Engine.Structure.Elements.Create`.

As such methods like `BH.Engine.Reflection.Create.Type(string)` (which returns `Type`) ends up as `Create.System.Type`, not `Create.Reflection.Type`.

This PR corrects this.

<!-- Add short description of what has been fixed -->


### Test files
<!-- Link to test files to validate the proposed changes -->
[namespaces.xlsx](https://github.com/BHoM/Excel_Toolkit/files/3277268/namespaces.xlsx)

This has methods from all the `BHoM_Engine` projects, if you calculate on `master` you should get `#NAME!` errors for some of them, this PR should resolve that.

### Changelog
<!-- Text to go into changelog if applicable -->
<!-- Please see https://github.com/BHoM/documentation/wiki/changelog for guidelines -->


### Additional comments
<!-- As required -->

2019-06-12 08:51 UTC, awakeman commented
Regarding those errors and warnings i'll raise some issues from them. I believe that the RhinoCommon, Grasshopper and Revit dll's that attempt to load are due to dependencies from the Rhino, Grasshopper and Revit toolkits and are non-fatal.

The errors in registering the Templated `CreateType` and `CreateCustom` formulae would be good to fix but are due to `<`,`>` and `,` being illegal characters in a formula name. As far as I am aware the affected types are very unlikely to be desired in a `FilterQuery`, for example.

Will raise some issues for these.

2019-06-12 12:27 UTC, rwemay commented
Great, thanks. Let's add the fixes that we can to this PR as they all relate to start up. Great to get as many of these bugs squashed as possible so we're building on a more solid opening-performance platform.

2019-06-13 13:28 UTC, awakeman commented
Closes #100

Sometimes excel process continues after all windows are closed, caused by there being unreleased COM objects. Added a commit to make sure we release them correctly to avoid this.

2019-06-13 19:16 UTC, michaldengusiak commented
@awakeman 
I tested this and is building fine and is working. It is faster it takes for me 16 sek compare to 2 min before. Great

The only comment I have because we do not have content menu AND we type in excel differently compate to other UIs is much more difficult to find methods. I hope we find in future some way to load menu or provide search just to make templates. Once is set up loading time should be priority. Maybe we can still have some way to run long version a debug/ script creation option ? 


Excel
![image](https://user-images.githubusercontent.com/26113670/59460560-4f757300-8e17-11e9-9754-dd75ae4a1d6a.png)
Dynamo, GH
![image](https://user-images.githubusercontent.com/26113670/59460670-8e0b2d80-8e17-11e9-8de5-bbeb92bf3760.png)
![image](https://user-images.githubusercontent.com/26113670/59460531-3a004900-8e17-11e9-85f9-f70436adc68a.png)

2019-06-14 08:04 UTC, awakeman commented
Nice catch @michaldengusiak, thanks, that should be fixed now.

2019-06-14 08:48 UTC, michaldengusiak approved these changes
@awakeman 

thanks we have now
`=Create.Environment.Elements.Building?by_String_Double_Double_Double_BuildingType("aa")`

### so normally this is excel rule..
we have method in BHoM that is used in _GH and Dynamo_:
`BH.Engine.Environment.Query.PanelsContainingPoint`

with _Excel_ we delete first two `BH.Engine` or `BH.oM`
`Environment.Query.PanelsContainingPoint`
and change order
`Query.Environment.PanelsContainingPoint`

personally, If I could change  I would prefer to type full 1:1 formula even if is long - would be consistent  but if this is what we agreed then I am  fine...
we just need to make clear documentation to everyone how to type...

2019-06-14 09:01 UTC, rwemay commented
@michaldengusiak , I agree with you - 1:1 is better to align across all (current) platforms, *although* in Excel, having the long method/namespace names does make it a bit trickier to nest formulae - the formula quickly gets very long. I would therefore err on the side of shortened. @IsakNaslundBh you've used Excel_Toolkit as much/more than any - what are your thoughts? 

Given that profiling the formula creation has shown that it's not expensive/a governing factor, would it be crazy to keep both....? So you can type with intellisense either BH.Engine.Environment or Environment.Query etc. 

This is a relatively big decision as it will obviously break lots of spreadsheets if we change direction later, but perhaps by allowing both we can take care of this more easily...?

2019-06-14 09:14 UTC, rwemay approved these changes
Approving this so that we can move forwards with further testing, as it addresses one key issue of startup performance (which itself is hindering testing). 

As far as testing - @michaldengusiak  has tested/approved with comments, and I have been using Excel with a couple of workbooks from this branch for a week and it appears to be working.

2019-06-14 09:15 UTC, rwemay commented
Merging this and will close, and move the suggestion of supporting multiple namespace formula options as a separate issue for discussion.

2019-06-14 09:15 UTC, merged